drop table space_station_log;
drop table space_ship_dock;
drop table space_ships;
drop table space_stations;

create table space_stations (
  id integer generated by default as identity primary key,
  name varchar2(1000) not null unique,
  max_docking_slots integer not null,
  used_docking_slots integer default 0,
  check ( used_docking_slots <= max_docking_slots)
);

insert into space_stations (id, name, max_docking_slots ) values ( 1, 'Tatooine-Alpha', 5);
insert into space_stations (id, name, max_docking_slots ) values ( 2, 'Hoth-Gamma', 7);
insert into space_stations (id, name, max_docking_slots ) values ( 3, 'Coruscant Main', 25);

create table space_ships (
  id integer generated by default as identity primary key,
  name varchar2(1000) not null unique,
  status varchar2(50) default 'FLYING' not null,
  check (status in ('FLYING', 'DOCKED', 'DESTROYED'))
);

insert into space_ships ( id, name ) values ( 1, 'Millennium Falcon');
insert into space_ships ( id, name ) values ( 2, 'Trader AC23-T');
insert into space_ships ( id, name ) values ( 3, 'X-Wing 1513');
insert into space_ships ( id, name ) values ( 4, 'Vaders Vessel');

create table space_ship_dock (
  ship_id integer not null,
  station_id integer not null,
  primary key (ship_id, station_id),
  foreign key ( ship_id ) references space_ships( id ),
  foreign key ( station_id ) references space_stations( id )
);

create table space_station_log (
  id integer generated always as identity primary key,
  message varchar2(4000) not null,
  created timestamp default current_timestamp not null
);

-- How to dock
insert into space_ship_dock ( ship_id, station_id )
  values ( 1, 1 );

update space_stations set
  used_docking_slots = used_docking_slots+1
  where id = 1;

update space_ships set
  status = 'DOCKED'
  where id = 1;

insert into space_station_log ( message )
  values ('Millennium Falcon docked to Tatooine-Alpha');

commit;


select ship.name
from space_ships ship
  inner join space_ship_dock dock on ship.id = dock.ship_id
  inner join space_stations station on dock.station_id = station.id
where station.name = 'Tatooine-Alpha';


-- transform to JSON
select
  json_serialize (
    json_object(
      'type' value 'station',
      station.id,
      station.name,
      station.max_docking_slots,
      'docked_ships' value json_arrayagg(
        json_object(
          'type' value 'ship',
          ship.id,
          ship.name
        )
      )
    )
    pretty
  )
from space_ships ship
  inner join space_ship_dock dock on ship.id = dock.ship_id
  inner join space_stations station on dock.station_id = station.id
where station.name = 'Tatooine-Alpha'
group by station.id, station.name, station.max_docking_slots;