/* Prepare test-tables */
set feedback off
create table force_measures (
    id integer generated by default on null as identity primary key not null,
    character varchar2(256),
    force_power number(32,2),
    measure_date date
);

create table force_measures2 (
    id integer generated by default on null as identity primary key not null,
    character varchar2(256),
    force_power number(32,2),
    measure_date date
);

insert into force_measures ( character, force_power, measure_date ) values ( 'Han Solo', 12.5, to_date('2021-05-29','YYYY-MM-DD') );
insert into force_measures ( character, force_power, measure_date ) values ( 'Anakin Skywalker', 100500.33, date '2020-09-05' );
insert into force_measures ( character, force_power, measure_date ) values ( 'Mace Windu', 7899, date '1984-03-23' );

commit;

set feedback on

/* Step 1: Export */
--alter session set nls_numeric_characters = '.,';

--spool sqlcl_load_numeric.csv
--select /*csv*/ * from force_measures;
--spool off

/* Step 2: Import */
--set load locale American America
alter session set nls_numeric_characters = '.,';
alter session set nls_date_format = 'DD-MON-YY';
alter session set nls_language = 'American';
load force_measures2 sqlcl_load_numeric.csv

select * from force_measures2;

/* Cleanup: */
set feedback off
drop table force_measures;
drop table force_measures2;

exit